import { SmallImagesState } from "./types";

export const smallImages: SmallImagesState[] = [
  {
    src: "/image/almond.svg",
    initialTop: 0,
    initialLeft: 300,
    width: 40,
    height: 40,
    rotate: 90,
  },
  {
    src: "/image/almond.svg",
    initialTop: 170,
    initialLeft: 70,
    width: 40,
    height: 40,
    rotate: 180,
  },
  {
    src: "/image/almond.svg",
    initialTop: 390,
    initialLeft: 70,
    width: 40,
    height: 40,
    rotate: 90,
  },
  {
    src: "/image/almond.svg",
    initialTop: 380,
    initialLeft: 290,
    width: 40,
    height: 40,
    rotate: 90,
  },
  {
    src: "/image/almond.svg",
    initialTop: 401,
    initialLeft: 490,
    width: 40,
    height: 40,
    rotate: 90,
  },
  {
    src: "/image/almond.svg",
    initialTop: 260,
    initialLeft: 540,
    width: 40,
    height: 40,
    rotate: 90,
  },
  {
    src: "/image/macaron1.svg",
    initialTop: 0,
    initialLeft: 130,
    width: 100,
    height: 100,
    rotate: 0,
  },
  {
    src: "/image/macaron2.svg",
    initialTop: 20,
    initialLeft: 550,
    width: 100,
    height: 100,
    rotate: 100,
  },
  {
    src: "/image/macaron3.svg",
    initialTop: 330,
    initialLeft: 520,
    width: 100,
    height: 100,
    rotate: 100,
  },
  {
    src: "/image/macaron3.svg",
    initialTop: 380,
    initialLeft: 170,
    width: 100,
    height: 100,
    rotate: 100,
  },
  {
    src: "/image/macaron4.svg",
    initialTop: 190,
    initialLeft: -20,
    width: 130,
    height: 130,
    rotate: 100,
  },
  {
    src: "/image/macaron5.svg",
    initialTop: 180,
    initialLeft: 590,
    width: 70,
    height: 70,
    rotate: 100,
  },
  {
    src: "/image/macaron6.svg",
    initialTop: 280,
    initialLeft: 80,
    width: 100,
    height: 100,
    rotate: 100,
  },
];
